[workspace]
members = [
    # Tasks
    "add",
    "comm",
    "perc",
    "ini",
    "polka",
    "trust",
    "flatmap",
    "pstack",
    "chip8",
    "mpsc",
    "fswalk",
    "stdmacro",
    "gc",
    "orm",
    "pargrep",
    "tcp_proxy",
]
resolver = "2"
